export interface Currency {
  code: string;
  name: string;
  symbol: string;
  country: string;
  flag: string;
}

export const WORLD_CURRENCIES: Currency[] = [
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", country: "United Arab Emirates", flag: "🇦🇪" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", country: "Afghanistan", flag: "🇦🇫" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", country: "Albania", flag: "🇦🇱" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", country: "Armenia", flag: "🇦🇲" },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", country: "Netherlands Antilles", flag: "🇳🇱" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", country: "Angola", flag: "🇦🇴" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", country: "Argentina", flag: "🇦🇷" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", country: "Australia", flag: "🇦🇺" },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", country: "Aruba", flag: "🇦🇼" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", country: "Azerbaijan", flag: "🇦🇿" },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", symbol: "KM", country: "Bosnia & Herzegovina", flag: "🇧🇦" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", country: "Barbados", flag: "🇧🇧" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", country: "Bangladesh", flag: "🇧🇩" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", country: "Bulgaria", flag: "🇧🇬" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", country: "Bahrain", flag: "🇧🇭" },
  { code: "BIF", name: "Burundian Franc", symbol: "Fr", country: "Burundi", flag: "🇧🇮" },
  { code: "BMD", name: "Bermudan Dollar", symbol: "$", country: "Bermuda", flag: "🇧🇲" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", country: "Brunei", flag: "🇧🇳" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", country: "Bolivia", flag: "🇧🇴" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", country: "Brazil", flag: "🇧🇷" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", country: "Bahamas", flag: "🇧🇸" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu", country: "Bhutan", flag: "🇧🇹" },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", country: "Botswana", flag: "🇧🇼" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", country: "Belarus", flag: "🇧🇾" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", country: "Belize", flag: "🇧🇿" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", country: "Canada", flag: "🇨🇦" },
  { code: "CDF", name: "Congolese Franc", symbol: "Fr", country: "DR Congo", flag: "🇨🇩" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr", country: "Switzerland", flag: "🇨🇭" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", country: "Chile", flag: "🇨🇱" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", country: "China", flag: "🇨🇳" },
  { code: "COP", name: "Colombian Peso", symbol: "$", country: "Colombia", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", country: "Costa Rica", flag: "🇨🇷" },
  { code: "CUP", name: "Cuban Peso", symbol: "$", country: "Cuba", flag: "🇨🇺" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", country: "Cape Verde", flag: "🇨🇻" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", country: "Czech Republic", flag: "🇨🇿" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fr", country: "Djibouti", flag: "🇩🇯" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", country: "Denmark", flag: "🇩🇰" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", country: "Dominican Republic", flag: "🇩🇴" },
  { code: "DZD", name: "Algerian Dinar", symbol: "دج", country: "Algeria", flag: "🇩🇿" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", country: "Egypt", flag: "🇪🇬" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", country: "Eritrea", flag: "🇪🇷" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", country: "Ethiopia", flag: "🇪🇹" },
  { code: "EUR", name: "Euro", symbol: "€", country: "European Union", flag: "🇪🇺" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", country: "Fiji", flag: "🇫🇯" },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£", country: "Falkland Islands", flag: "🇫🇰" },
  { code: "GBP", name: "British Pound", symbol: "£", country: "United Kingdom", flag: "🇬🇧" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", country: "Georgia", flag: "🇬🇪" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", country: "Ghana", flag: "🇬🇭" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", country: "Gibraltar", flag: "🇬🇮" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", country: "Gambia", flag: "🇬🇲" },
  { code: "GNF", name: "Guinean Franc", symbol: "Fr", country: "Guinea", flag: "🇬🇳" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", country: "Guatemala", flag: "🇬🇹" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", country: "Guyana", flag: "🇬🇾" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", country: "Hong Kong", flag: "🇭🇰" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", country: "Honduras", flag: "🇭🇳" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", country: "Croatia", flag: "🇭🇷" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", country: "Haiti", flag: "🇭🇹" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", country: "Hungary", flag: "🇭🇺" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", country: "Indonesia", flag: "🇮🇩" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", country: "Israel", flag: "🇮🇱" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", country: "India", flag: "🇮🇳" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", country: "Iraq", flag: "🇮🇶" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", country: "Iran", flag: "🇮🇷" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", country: "Iceland", flag: "🇮🇸" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", country: "Jamaica", flag: "🇯🇲" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JD", country: "Jordan", flag: "🇯🇴" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", country: "Japan", flag: "🇯🇵" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", country: "Kenya", flag: "🇰🇪" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", country: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", country: "Cambodia", flag: "🇰🇭" },
  { code: "KMF", name: "Comorian Franc", symbol: "Fr", country: "Comoros", flag: "🇰🇲" },
  { code: "KPW", name: "North Korean Won", symbol: "₩", country: "North Korea", flag: "🇰🇵" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", country: "South Korea", flag: "🇰🇷" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD", country: "Kuwait", flag: "🇰🇼" },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", country: "Cayman Islands", flag: "🇰🇾" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", country: "Kazakhstan", flag: "🇰🇿" },
  { code: "LAK", name: "Laotian Kip", symbol: "₭", country: "Laos", flag: "🇱🇦" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", country: "Lebanon", flag: "🇱🇧" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", country: "Liberia", flag: "🇱🇷" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", country: "Lesotho", flag: "🇱🇸" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", country: "Libya", flag: "🇱🇾" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", country: "Morocco", flag: "🇲🇦" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", country: "Moldova", flag: "🇲🇩" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", country: "Madagascar", flag: "🇲🇬" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", country: "North Macedonia", flag: "🇲🇰" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", country: "Myanmar", flag: "🇲🇲" },
  { code: "MNT", name: "Mongolian Tögrög", symbol: "₮", country: "Mongolia", flag: "🇲🇳" },
  { code: "MOP", name: "Macanese Pataca", symbol: "P", country: "Macau", flag: "🇲🇴" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", country: "Mauritania", flag: "🇲🇷" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", country: "Mauritius", flag: "🇲🇺" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", country: "Maldives", flag: "🇲🇻" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", country: "Malawi", flag: "🇲🇼" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", country: "Mexico", flag: "🇲🇽" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", country: "Malaysia", flag: "🇲🇾" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", country: "Mozambique", flag: "🇲🇿" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", country: "Namibia", flag: "🇳🇦" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", country: "Nigeria", flag: "🇳🇬" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", country: "Nicaragua", flag: "🇳🇮" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", country: "Norway", flag: "🇳🇴" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", country: "Nepal", flag: "🇳🇵" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", country: "New Zealand", flag: "🇳🇿" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", country: "Oman", flag: "🇴🇲" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", country: "Panama", flag: "🇵🇦" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/.", country: "Peru", flag: "🇵🇪" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", country: "Papua New Guinea", flag: "🇵🇬" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", country: "Philippines", flag: "🇵🇭" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", country: "Pakistan", flag: "🇵🇰" },
  { code: "PLN", name: "Polish Złoty", symbol: "zł", country: "Poland", flag: "🇵🇱" },
  { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲", country: "Paraguay", flag: "🇵🇾" },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", country: "Qatar", flag: "🇶🇦" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", country: "Romania", flag: "🇷🇴" },
  { code: "RSD", name: "Serbian Dinar", symbol: "din", country: "Serbia", flag: "🇷🇸" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", country: "Russia", flag: "🇷🇺" },
  { code: "RWF", name: "Rwandan Franc", symbol: "Fr", country: "Rwanda", flag: "🇷🇼" },
  { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", country: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", country: "Solomon Islands", flag: "🇸🇧" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", country: "Seychelles", flag: "🇸🇨" },
  { code: "SDG", name: "Sudanese Pound", symbol: "£", country: "Sudan", flag: "🇸🇩" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", country: "Sweden", flag: "🇸🇪" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", country: "Singapore", flag: "🇸🇬" },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", country: "Saint Helena", flag: "🇸🇭" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le", country: "Sierra Leone", flag: "🇸🇱" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", country: "Somalia", flag: "🇸🇴" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", country: "Suriname", flag: "🇸🇷" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", country: "South Sudan", flag: "🇸🇸" },
  { code: "STN", name: "São Tomé & Príncipe Dobra", symbol: "Db", country: "São Tomé & Príncipe", flag: "🇸🇹" },
  { code: "SYP", name: "Syrian Pound", symbol: "£", country: "Syria", flag: "🇸🇾" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", country: "Eswatini", flag: "🇸🇿" },
  { code: "THB", name: "Thai Baht", symbol: "฿", country: "Thailand", flag: "🇹🇭" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", country: "Tajikistan", flag: "🇹🇯" },
  { code: "TMT", name: "Turkmenistan Manat", symbol: "T", country: "Turkmenistan", flag: "🇹🇲" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", country: "Tunisia", flag: "🇹🇳" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", country: "Tonga", flag: "🇹🇴" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", country: "Turkey", flag: "🇹🇷" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "TT$", country: "Trinidad & Tobago", flag: "🇹🇹" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", country: "Taiwan", flag: "🇹🇼" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "Sh", country: "Tanzania", flag: "🇹🇿" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", country: "Ukraine", flag: "🇺🇦" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "Sh", country: "Uganda", flag: "🇺🇬" },
  { code: "USD", name: "US Dollar", symbol: "$", country: "United States", flag: "🇺🇸" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", country: "Uruguay", flag: "🇺🇾" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "so'm", country: "Uzbekistan", flag: "🇺🇿" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.", country: "Venezuela", flag: "🇻🇪" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", country: "Vietnam", flag: "🇻🇳" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt", country: "Vanuatu", flag: "🇻🇺" },
  { code: "WST", name: "Samoan Tala", symbol: "T", country: "Samoa", flag: "🇼🇸" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "Fr", country: "Central Africa", flag: "🌍" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", country: "East Caribbean", flag: "🌎" },
  { code: "XOF", name: "West African CFA Franc", symbol: "Fr", country: "West Africa", flag: "🌍" },
  { code: "XPF", name: "CFP Franc", symbol: "Fr", country: "French Polynesia", flag: "🇵🇫" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", country: "Yemen", flag: "🇾🇪" },
  { code: "ZAR", name: "South African Rand", symbol: "R", country: "South Africa", flag: "🇿🇦" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", country: "Zambia", flag: "🇿🇲" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", country: "Zimbabwe", flag: "🇿🇼" },
];

export const POPULAR_CURRENCIES = ["USD", "EUR", "GBP", "PKR", "SAR", "AED", "INR", "JPY", "CNY", "CAD", "AUD", "CHF"];
